export default {
    maxexpandId: 95,
    treelist: [{
      id: 1,
      name: '北京市',
      ProSort: 1,
      remark: '直辖市',
      pid: 1,
      isEdit: false,
      children: [{
        id: 35,
        name: '朝阳区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 36,
        name: '海淀区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 37,
        name: '房山区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 38,
        name: '丰台区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 39,
        name: '昌平区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 40,
        name: '大兴区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }]
    }, {
      id: 2,
      name: '天津市',
      ProSort: 2,
      remark: '直辖市',
      pid: 1,
      isEdit: false,
      children: [{
        id: 41,
        name: '北辰区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 42,
        name: '河北区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 43,
        name: '西青区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 44,
        name: '东丽区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }]
    }, {
      id: 3,
      name: '河北省',
      level:1,
      ProSort: 5,
      remark: '省份',
      pid: 1,
      isEdit: false,
      children: [{
        id: 45,
        name: '衡水市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 46,
        name: '张家口市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 47,
        name: '秦皇岛市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 48,
        name: '承德市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 49,
        name: '邯郸市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }]
    }, {
      id: 4,
      name: '山西省',
      ProSort: 6,
      remark: '省份',
      pid: 1,
      isEdit: false,
      children: [{
        id: 50,
        name: '大同市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }]
    }, {
      id: 6,
      name: '辽宁省',
      ProSort: 8,
      remark: '省份',
      pid: 1,
      isEdit: false,
      children: [{
        id: 52,
        name: '大连市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 53,
        name: '太原市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }]
    }, {
      id: 21,
      name: '广西壮族自治区',
      ProSort: 28,
      remark: '自治区',
      pid: 1,
      isEdit: false,
      children: [{
        id: 69,
        name: '玉林市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 86,
        name: '贺州市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }]
    }, {
      id: 23,
      name: '陕西省',
      ProSort: 27,
      remark: '省份',
      pid: 1,
      isEdit: false,
      children: [{
        id: 71,
        name: '咸阳市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 87,
        name: '安康市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }]
    }, {
      id: 24,
      name: '新疆维吾尔自治区',
      ProSort: 31,
      remark: '自治区',
      pid: 1,
      isEdit: false,
      children: [{
        id: 72,
        name: '乌鲁木齐市',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 88,
        name: '和田地区',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }, {
        id: 89,
        name: '阿勒泰州',
        pid: 2,
        remark: '',
        isEdit: false,
        children: []
      }]
    }]
  }